// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class PeriodStarts extends Table
    with TableInfo<PeriodStarts, PeriodStartsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  PeriodStarts(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> date = GeneratedColumn<String>(
    'date',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [date];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'period_starts';
  @override
  Set<GeneratedColumn> get $primaryKey => {date};
  @override
  PeriodStartsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return PeriodStartsData(
      date: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}date'],
      )!,
    );
  }

  @override
  PeriodStarts createAlias(String alias) {
    return PeriodStarts(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(date)'];
  @override
  bool get dontWriteConstraints => true;
}

class PeriodStartsData extends DataClass
    implements Insertable<PeriodStartsData> {
  final String date;
  const PeriodStartsData({required this.date});
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['date'] = Variable<String>(date);
    return map;
  }

  PeriodStartsCompanion toCompanion(bool nullToAbsent) {
    return PeriodStartsCompanion(date: Value(date));
  }

  factory PeriodStartsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return PeriodStartsData(date: serializer.fromJson<String>(json['date']));
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{'date': serializer.toJson<String>(date)};
  }

  PeriodStartsData copyWith({String? date}) =>
      PeriodStartsData(date: date ?? this.date);
  PeriodStartsData copyWithCompanion(PeriodStartsCompanion data) {
    return PeriodStartsData(
      date: data.date.present ? data.date.value : this.date,
    );
  }

  @override
  String toString() {
    return (StringBuffer('PeriodStartsData(')
          ..write('date: $date')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => date.hashCode;
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is PeriodStartsData && other.date == this.date);
}

class PeriodStartsCompanion extends UpdateCompanion<PeriodStartsData> {
  final Value<String> date;
  final Value<int> rowid;
  const PeriodStartsCompanion({
    this.date = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  PeriodStartsCompanion.insert({
    required String date,
    this.rowid = const Value.absent(),
  }) : date = Value(date);
  static Insertable<PeriodStartsData> custom({
    Expression<String>? date,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (date != null) 'date': date,
      if (rowid != null) 'rowid': rowid,
    });
  }

  PeriodStartsCompanion copyWith({Value<String>? date, Value<int>? rowid}) {
    return PeriodStartsCompanion(
      date: date ?? this.date,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (date.present) {
      map['date'] = Variable<String>(date.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('PeriodStartsCompanion(')
          ..write('date: $date, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DayEntries extends Table with TableInfo<DayEntries, DayEntriesData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DayEntries(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> date = GeneratedColumn<String>(
    'date',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> flow = GeneratedColumn<String>(
    'flow',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> note = GeneratedColumn<String>(
    'note',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [date, flow, note];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'day_entries';
  @override
  Set<GeneratedColumn> get $primaryKey => {date};
  @override
  DayEntriesData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return DayEntriesData(
      date: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}date'],
      )!,
      flow: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}flow'],
      ),
      note: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}note'],
      ),
    );
  }

  @override
  DayEntries createAlias(String alias) {
    return DayEntries(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(date)'];
  @override
  bool get dontWriteConstraints => true;
}

class DayEntriesData extends DataClass implements Insertable<DayEntriesData> {
  final String date;
  final String? flow;
  final String? note;
  const DayEntriesData({required this.date, this.flow, this.note});
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['date'] = Variable<String>(date);
    if (!nullToAbsent || flow != null) {
      map['flow'] = Variable<String>(flow);
    }
    if (!nullToAbsent || note != null) {
      map['note'] = Variable<String>(note);
    }
    return map;
  }

  DayEntriesCompanion toCompanion(bool nullToAbsent) {
    return DayEntriesCompanion(
      date: Value(date),
      flow: flow == null && nullToAbsent ? const Value.absent() : Value(flow),
      note: note == null && nullToAbsent ? const Value.absent() : Value(note),
    );
  }

  factory DayEntriesData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return DayEntriesData(
      date: serializer.fromJson<String>(json['date']),
      flow: serializer.fromJson<String?>(json['flow']),
      note: serializer.fromJson<String?>(json['note']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'date': serializer.toJson<String>(date),
      'flow': serializer.toJson<String?>(flow),
      'note': serializer.toJson<String?>(note),
    };
  }

  DayEntriesData copyWith({
    String? date,
    Value<String?> flow = const Value.absent(),
    Value<String?> note = const Value.absent(),
  }) => DayEntriesData(
    date: date ?? this.date,
    flow: flow.present ? flow.value : this.flow,
    note: note.present ? note.value : this.note,
  );
  DayEntriesData copyWithCompanion(DayEntriesCompanion data) {
    return DayEntriesData(
      date: data.date.present ? data.date.value : this.date,
      flow: data.flow.present ? data.flow.value : this.flow,
      note: data.note.present ? data.note.value : this.note,
    );
  }

  @override
  String toString() {
    return (StringBuffer('DayEntriesData(')
          ..write('date: $date, ')
          ..write('flow: $flow, ')
          ..write('note: $note')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(date, flow, note);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is DayEntriesData &&
          other.date == this.date &&
          other.flow == this.flow &&
          other.note == this.note);
}

class DayEntriesCompanion extends UpdateCompanion<DayEntriesData> {
  final Value<String> date;
  final Value<String?> flow;
  final Value<String?> note;
  final Value<int> rowid;
  const DayEntriesCompanion({
    this.date = const Value.absent(),
    this.flow = const Value.absent(),
    this.note = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  DayEntriesCompanion.insert({
    required String date,
    this.flow = const Value.absent(),
    this.note = const Value.absent(),
    this.rowid = const Value.absent(),
  }) : date = Value(date);
  static Insertable<DayEntriesData> custom({
    Expression<String>? date,
    Expression<String>? flow,
    Expression<String>? note,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (date != null) 'date': date,
      if (flow != null) 'flow': flow,
      if (note != null) 'note': note,
      if (rowid != null) 'rowid': rowid,
    });
  }

  DayEntriesCompanion copyWith({
    Value<String>? date,
    Value<String?>? flow,
    Value<String?>? note,
    Value<int>? rowid,
  }) {
    return DayEntriesCompanion(
      date: date ?? this.date,
      flow: flow ?? this.flow,
      note: note ?? this.note,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (date.present) {
      map['date'] = Variable<String>(date.value);
    }
    if (flow.present) {
      map['flow'] = Variable<String>(flow.value);
    }
    if (note.present) {
      map['note'] = Variable<String>(note.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('DayEntriesCompanion(')
          ..write('date: $date, ')
          ..write('flow: $flow, ')
          ..write('note: $note, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DaySymptoms extends Table with TableInfo<DaySymptoms, DaySymptomsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DaySymptoms(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> date = GeneratedColumn<String>(
    'date',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> symptomKey = GeneratedColumn<String>(
    'symptom_key',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [date, symptomKey];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'day_symptoms';
  @override
  Set<GeneratedColumn> get $primaryKey => {date, symptomKey};
  @override
  DaySymptomsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return DaySymptomsData(
      date: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}date'],
      )!,
      symptomKey: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}symptom_key'],
      )!,
    );
  }

  @override
  DaySymptoms createAlias(String alias) {
    return DaySymptoms(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(date, symptom_key)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DaySymptomsData extends DataClass implements Insertable<DaySymptomsData> {
  final String date;
  final String symptomKey;
  const DaySymptomsData({required this.date, required this.symptomKey});
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['date'] = Variable<String>(date);
    map['symptom_key'] = Variable<String>(symptomKey);
    return map;
  }

  DaySymptomsCompanion toCompanion(bool nullToAbsent) {
    return DaySymptomsCompanion(
      date: Value(date),
      symptomKey: Value(symptomKey),
    );
  }

  factory DaySymptomsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return DaySymptomsData(
      date: serializer.fromJson<String>(json['date']),
      symptomKey: serializer.fromJson<String>(json['symptomKey']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'date': serializer.toJson<String>(date),
      'symptomKey': serializer.toJson<String>(symptomKey),
    };
  }

  DaySymptomsData copyWith({String? date, String? symptomKey}) =>
      DaySymptomsData(
        date: date ?? this.date,
        symptomKey: symptomKey ?? this.symptomKey,
      );
  DaySymptomsData copyWithCompanion(DaySymptomsCompanion data) {
    return DaySymptomsData(
      date: data.date.present ? data.date.value : this.date,
      symptomKey: data.symptomKey.present
          ? data.symptomKey.value
          : this.symptomKey,
    );
  }

  @override
  String toString() {
    return (StringBuffer('DaySymptomsData(')
          ..write('date: $date, ')
          ..write('symptomKey: $symptomKey')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(date, symptomKey);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is DaySymptomsData &&
          other.date == this.date &&
          other.symptomKey == this.symptomKey);
}

class DaySymptomsCompanion extends UpdateCompanion<DaySymptomsData> {
  final Value<String> date;
  final Value<String> symptomKey;
  final Value<int> rowid;
  const DaySymptomsCompanion({
    this.date = const Value.absent(),
    this.symptomKey = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  DaySymptomsCompanion.insert({
    required String date,
    required String symptomKey,
    this.rowid = const Value.absent(),
  }) : date = Value(date),
       symptomKey = Value(symptomKey);
  static Insertable<DaySymptomsData> custom({
    Expression<String>? date,
    Expression<String>? symptomKey,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (date != null) 'date': date,
      if (symptomKey != null) 'symptom_key': symptomKey,
      if (rowid != null) 'rowid': rowid,
    });
  }

  DaySymptomsCompanion copyWith({
    Value<String>? date,
    Value<String>? symptomKey,
    Value<int>? rowid,
  }) {
    return DaySymptomsCompanion(
      date: date ?? this.date,
      symptomKey: symptomKey ?? this.symptomKey,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (date.present) {
      map['date'] = Variable<String>(date.value);
    }
    if (symptomKey.present) {
      map['symptom_key'] = Variable<String>(symptomKey.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('DaySymptomsCompanion(')
          ..write('date: $date, ')
          ..write('symptomKey: $symptomKey, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class AppSettings extends Table with TableInfo<AppSettings, AppSettingsData> {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  AppSettings(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> settingKey = GeneratedColumn<String>(
    'setting_key',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> settingValue = GeneratedColumn<String>(
    'setting_value',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [settingKey, settingValue];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'app_settings';
  @override
  Set<GeneratedColumn> get $primaryKey => {settingKey};
  @override
  AppSettingsData map(Map<String, dynamic> data, {String? tablePrefix}) {
    final effectivePrefix = tablePrefix != null ? '$tablePrefix.' : '';
    return AppSettingsData(
      settingKey: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}setting_key'],
      )!,
      settingValue: attachedDatabase.typeMapping.read(
        DriftSqlType.string,
        data['${effectivePrefix}setting_value'],
      )!,
    );
  }

  @override
  AppSettings createAlias(String alias) {
    return AppSettings(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(setting_key)'];
  @override
  bool get dontWriteConstraints => true;
}

class AppSettingsData extends DataClass implements Insertable<AppSettingsData> {
  final String settingKey;
  final String settingValue;
  const AppSettingsData({required this.settingKey, required this.settingValue});
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    map['setting_key'] = Variable<String>(settingKey);
    map['setting_value'] = Variable<String>(settingValue);
    return map;
  }

  AppSettingsCompanion toCompanion(bool nullToAbsent) {
    return AppSettingsCompanion(
      settingKey: Value(settingKey),
      settingValue: Value(settingValue),
    );
  }

  factory AppSettingsData.fromJson(
    Map<String, dynamic> json, {
    ValueSerializer? serializer,
  }) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return AppSettingsData(
      settingKey: serializer.fromJson<String>(json['settingKey']),
      settingValue: serializer.fromJson<String>(json['settingValue']),
    );
  }
  @override
  Map<String, dynamic> toJson({ValueSerializer? serializer}) {
    serializer ??= driftRuntimeOptions.defaultSerializer;
    return <String, dynamic>{
      'settingKey': serializer.toJson<String>(settingKey),
      'settingValue': serializer.toJson<String>(settingValue),
    };
  }

  AppSettingsData copyWith({String? settingKey, String? settingValue}) =>
      AppSettingsData(
        settingKey: settingKey ?? this.settingKey,
        settingValue: settingValue ?? this.settingValue,
      );
  AppSettingsData copyWithCompanion(AppSettingsCompanion data) {
    return AppSettingsData(
      settingKey: data.settingKey.present
          ? data.settingKey.value
          : this.settingKey,
      settingValue: data.settingValue.present
          ? data.settingValue.value
          : this.settingValue,
    );
  }

  @override
  String toString() {
    return (StringBuffer('AppSettingsData(')
          ..write('settingKey: $settingKey, ')
          ..write('settingValue: $settingValue')
          ..write(')'))
        .toString();
  }

  @override
  int get hashCode => Object.hash(settingKey, settingValue);
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is AppSettingsData &&
          other.settingKey == this.settingKey &&
          other.settingValue == this.settingValue);
}

class AppSettingsCompanion extends UpdateCompanion<AppSettingsData> {
  final Value<String> settingKey;
  final Value<String> settingValue;
  final Value<int> rowid;
  const AppSettingsCompanion({
    this.settingKey = const Value.absent(),
    this.settingValue = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  AppSettingsCompanion.insert({
    required String settingKey,
    required String settingValue,
    this.rowid = const Value.absent(),
  }) : settingKey = Value(settingKey),
       settingValue = Value(settingValue);
  static Insertable<AppSettingsData> custom({
    Expression<String>? settingKey,
    Expression<String>? settingValue,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (settingKey != null) 'setting_key': settingKey,
      if (settingValue != null) 'setting_value': settingValue,
      if (rowid != null) 'rowid': rowid,
    });
  }

  AppSettingsCompanion copyWith({
    Value<String>? settingKey,
    Value<String>? settingValue,
    Value<int>? rowid,
  }) {
    return AppSettingsCompanion(
      settingKey: settingKey ?? this.settingKey,
      settingValue: settingValue ?? this.settingValue,
      rowid: rowid ?? this.rowid,
    );
  }

  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    final map = <String, Expression>{};
    if (settingKey.present) {
      map['setting_key'] = Variable<String>(settingKey.value);
    }
    if (settingValue.present) {
      map['setting_value'] = Variable<String>(settingValue.value);
    }
    if (rowid.present) {
      map['rowid'] = Variable<int>(rowid.value);
    }
    return map;
  }

  @override
  String toString() {
    return (StringBuffer('AppSettingsCompanion(')
          ..write('settingKey: $settingKey, ')
          ..write('settingValue: $settingValue, ')
          ..write('rowid: $rowid')
          ..write(')'))
        .toString();
  }
}

class DatabaseAtV2 extends GeneratedDatabase {
  DatabaseAtV2(QueryExecutor e) : super(e);
  late final PeriodStarts periodStarts = PeriodStarts(this);
  late final DayEntries dayEntries = DayEntries(this);
  late final DaySymptoms daySymptoms = DaySymptoms(this);
  late final AppSettings appSettings = AppSettings(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    periodStarts,
    dayEntries,
    daySymptoms,
    appSettings,
  ];
  @override
  int get schemaVersion => 2;
}
